# run_migrations = true
listen_addr = ":3000"
data_dir = "/Some/Dir"
odic_client_id = "<ODIC_CLIENT_ID>"
odic_client_secret = "<ODIC_CLIENT_SECRET>"
odic_issuer_url = "<ODIC_ISSUER_URL>"
odic_redirect_url = "https://customdomain.com/api/v1/auth/callback"
jwt_secret = "" # Example: openssl rand -base64 32
